version: '3.4'

services:
  agent:
    image: node:14.11.0-stretch-slim
    volumes:
      - ../:/app
    environment:
      - PROJECT
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
