version: '3.4'

services:
  agent:
    image: node:14.3.0
    working_dir: /app
    volumes:
      - ../:/app
    environment:
      - PROJECT
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
