version: '3.4'

services:
  agent:
    image: node:14.3.0
    working_dir: /app
    volumes:
      - ../:/app
      - ${BUILDKITE_AGENT_BINARY_PATH:-/usr/bin/buildkite-agent}:/usr/bin/buildkite-agent
    environment:
      - PROJECT
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILD_OPTS
      - RELEASE_TYPE
      - MAJOR_VERSION
      - BUILDKITE_AGENT_ACCESS_TOKEN
